name: update_atcoder_id

on:
  schedule: # execute every 24 hours
    - cron: '*/10 * * * 1-5'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: job
        run: sh cron/update_atcoder_user_history.sh
        env:
          email: ${{ secrets.EMAIL }}
          password: ${{ secrets.PASSWORD }}